### ISSUE TITLE
Eio.Flow.read hangs on closed flow

### ISSUE THREAD

**Issue by quartz55** [ocaml-multicore/eio#214] opened 2022-05-05 16:16 UTC
Not sure if I'm doing something wrong, but I've run into the following issue (on the Luv backend).

A fiber waiting on a `Eio.Flow.read` before another fiber closes it will hang forever, at least for a client type `Eio.Net.connect` flow.

I've managed to trim it down to the following case:

<details>
<summary>reproduce.ml</summary>

```ocaml
open Eio.Std

let main env =
  let run_client ~net ~addr =
    traceln "client on";
    Switch.run (fun sw ->
        let flow = Eio.Net.connect ~sw net addr in
        traceln "client <-> server";
        let read_loop () =
          let b = Cstruct.create 4 in
          traceln "client will be stuck after this";
          while true do
            Eio.Flow.read flow b |> ignore;
            traceln "unreachable"
          done
        in
        let d = "Hello from client" in
        traceln "client -> %S" d;
        Eio.Flow.copy_string d flow;
        Fiber.fork ~sw read_loop;
        Eio.Flow.close flow);
    traceln "client off"
  in
  let run_server socket =
    traceln "server on";
    Switch.run (fun sw ->
        Eio.Net.accept_sub socket ~sw
          (fun ~sw:_ flow _addr ->
            traceln "server <-> client";
            let b = Buffer.create 100 in
            Eio.Flow.copy flow (Eio.Flow.buffer_sink b);
            traceln "server <[EOF]- %S" (Buffer.contents b))
          ~on_error:(traceln "Error handling connection: %a" Fmt.exn));
    traceln "server off"
  in

  let net = Eio.Stdenv.net env in
  let addr = `Tcp (Eio.Net.Ipaddr.V4.loopback, 9999) in
  Switch.run @@ fun sw ->
  let server = Eio.Net.listen net ~sw ~reuse_addr:true ~backlog:5 addr in
  Fiber.both (fun () -> run_server server) (fun () -> run_client ~net ~addr)
```

</details>

Where the expected output would be:

```log
+server on
+client on
+client <-> server
+client -> "Hello from client"
+server <-> client
+client will be stuck after this
+server <[EOF]- "Hello from client"
+server off
*hangs forever*
```

**Comment by quartz55** [comment] 2022-05-07 14:15
Thanks, using `shutdown` instead does seem to sidestep the issue 👍

Funny thing, for reference, the source of my problem ended up being a Tls module loosely based on yours:
https://gitlab.com/talex5/gemini-eio/-/blob/master/src/tls_eio.ml#L128

Replacing that `close` call with a ``shutdown `Send`` made everything work 🙌

**Comment by talex5** [comment] 2022-05-13 10:31
> Funny thing, for reference, the source of my problem ended up being a Tls module loosely based on yours:

Hmm, yes, that Tls wrapper should probably now implement `Flow.two_way` and provide a `shutdown` operation that sends the close notify and then calls `shutdown` on the underlying flow.

Then `Tls_eio.close` can just close the underlying flow immediately

**Comment by talex5** [comment] 2022-08-26 13:11
In fact, I think continuing to wait is the correct behaviour. `close` is an operation on the file descriptor, not on the file (socket) itself. The socket itself is shut down when there are no more users of it, but the read is a valid user.

**Comment by talex5** [comment] 2022-09-27 11:25
Closing, as not a bug.

Note: there's now also a proper tls-eio package (https://github.com/mirleft/ocaml-tls/pull/451).

**Closed by talex5** 2022-09-27 11:25 UTC
